// simple utility to plot graphics on R². I don't think it's possible to represent
// surfaces from other dimensions. Basically, we generate a 2d array containing all the points
// generated by the given function, which is passed in the arguments. We also need to represent
// the x and y axis as for some reference
//
// I need to map the equation values, which will be stored as f64, to plain usize values, so I can
// represent them in the grid. Also, I need a way to map those values to an index, because I can
// only display values whose domain are between [0, term_width] and whose images are between
// [0, term_height].
//
// (domain_start, domain_end) -> (0, term_width)
// (image_start, image_end) -> (0, term_height)
//
// https://rosettacode.org/wiki/Map_range#Rust gives us a direct conversion formula.
mod plot;
mod parser;
mod lexer;
